export const mahasiswaData = [
    {
      ID_SISWA: "38606",
      NO_DAFTAR: "2212012488",
      NPM: "2209010298",
      NAMA_LENGKAP: "RAYHAN PRATAMA",
      JENIS_KELAMIN: "Laki-Laki",
      TGL_LAHIR: "2004-08-20 00:00:00.000",
      TEMPAT_LAHIR: "MEDAN",
      ALAMAT: "----",
      PROVINSI: "----",
      KABKOTA: "----",
      KELAS: "A1 Siang",
      ANGKATAN: 2022,
      FAKULTAS: "Ilmu Komputer dan Teknologi Informasi",
      ID_PRODI: 86,
      SINGKATAN_PRODI: "SI",
      PRODI: "Sistem Informasi",
      EMAIL: "agarayhan123@gmail.com",
      TAHUN_MASUK: 2022,
      ASAL_SEKOLAH: "----",
      PROVINSI_SEKOLAH: "----",
      KABKOTA_SEKOLAH: "----",
      STATUS_AKTIF: "Aktif",
      TGL_MASUK: "2022-10-02 18:29:49.000",
      TGL_LULUS: "----",
    },
    {
      ID_SISWA: "38607",
      NO_DAFTAR: "2212012489",
      NPM: "2209010297",
      NAMA_LENGKAP: "MUHAMMAD RIAN MIZARD",
      JENIS_KELAMIN: "Laki-Laki",
      TGL_LAHIR: "2002-06-25 00:00:00.000",
      TEMPAT_LAHIR: "Belawan",
      ALAMAT: "----",
      PROVINSI: "----",
      KABKOTA: "----",
      KELAS: "A1 Siang",
      ANGKATAN: 2022,
      FAKULTAS: "Ilmu Komputer dan Teknologi Informasi",
      ID_PRODI: 86,
      SINGKATAN_PRODI: "SI",
      PRODI: "Sistem Informasi",
      EMAIL: "muhammadrianmizard@gmail.com",
      TAHUN_MASUK: 2022,
      ASAL_SEKOLAH: "----",
      PROVINSI_SEKOLAH: "----",
      KABKOTA_SEKOLAH: "----",
      STATUS_AKTIF: "Aktif",
      TGL_MASUK: "2022-10-02 18:29:49.000",
      TGL_LULUS: "----",
    },
  ];
  